version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rastreamento
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=rastreamento
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 