version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=rastreamento
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_PASSWORD=${PGPASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 