server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:${DATABASE_PUBLIC_URL}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.rastreamento: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.hibernate: INFO
    org.postgresql: DEBUG
