server:
  port: 8080
  servlet:
    context-path: /auto-api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rastreamento
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1200000
      auto-commit: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: exchange-localizacoes
      routing-key: atualizacao.localizacao
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 100
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 10000
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  sql:
    init:
      mode: never
  profiles:
    active: dev

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true
    displayRequestDuration: true
    syntaxHighlight:
      activated: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    defaultModelRendering: model
    displayOperationId: false
    docExpansion: none
    showExtensions: true
    showCommonExtensions: true
    supportedSubmitMethods:
      - get
      - put
      - post
      - delete
      - options
      - head
      - patch
      - trace
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  paths-to-match: /**
  cache:
    disabled: true

tcp:
  server:
    port: 8090
    thread-pool-size: 100
    batch-size: 100
    batch-interval: 1000

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.rastreamento: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.hibernate: INFO
    org.postgresql: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: ${JWT_EXPIRATION:86400000} 